<a href="https://colab.research.google.com/github/KavindaKGD/DL_lab_01/blob/main/DL_Lab_01_Task_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1

In [2]:
#Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
import pandas as pd

Create a random 4x4 array from an exponential distribution

In [3]:
exp_array = np.random.exponential(scale=1.0, size=(4, 4))
print(exp_array)

[[0.1583618  3.34287689 0.4070207  0.7654807 ]
 [0.57092727 2.21397186 0.88588416 2.90903396]
 [1.98917284 1.880975   0.58393062 0.37455431]
 [0.11666304 1.67500722 1.00010845 2.72608599]]


Create a random 100000x1 array from the same exponential distribution and visualize the distribution histogram along with uniform and normal distributions